import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import Footer from "@/components/footer";
export const metadata: Metadata = {
  title: "Asian Mines And Minerals",
  description: "Generated by asina mines",
  icons: {
    icon: "https://asianmines.com/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
